#!/bin/bash

# Make sure only root can run this

if [[ $EUID -ne 0 ]]; then

   echo "ERROR: This script needs root permissions."
  echo
  echo "Since you are not logged in as root run 'su' before this command. (Default password is 'alpine' - it's wise to change this.)" 1>&2 
echo "Look here how to change it:"
echo "https://cydia.saurik.com/password.html"
   exit 1

fi

################
# Set Variables
GVERSION="iDenT1FIEr" #Identifier
# it would be awesome to have one script then have build.sh add the identifier to the script depending on what
# version is being built. there will be MANNNNY versions.
GVERSIONNAME="vErs10Nname" #Name

################
echo "---Welcome to $GVERSIONNAME.---"
echo "Made by EthanRDoesMC and mehulrao."

case $1 in
"") 
echo
echo "---USAGE---"
echo
echo "$0 hold: run directly after install of $GVERSIONNAME. It will prevent cydia from removing Gandalf automatically."
echo
echo "$0 rmhold: run before update or uninstall to let Cydia remove $GVERSIONNAME."
 ;;
"hold")
echo "Add hold to $GVERSIONNAME..."
echo "$GVERSION hold" | dpkg --set-selections
 ;;
 "rmhold")
echo "Remove hold from $GVERSIONNAME..."
echo "$GVERSION install" | dpkg --set-selections
 ;;
 *)
echo "ERROR: invalid parameter $1"
echo
echo "---USAGE---"
echo
echo "$0 hold: run directly after install of $GVERSIONNAME. It will prevent cydia from removing Gandalf automatically"
echo
echo "$0 rmhold: run before update or uninstall to let Cydia remove $GVERSIONNAME."
;;
 esac
 echo "Thank you for using Gandalf."
