#!/bin/bash

# Make sure only root can run this

if [[ $EUID -ne 0 ]]; then

   echo "ERROR: This script needs root permissions."
  echo
  echo "Since you are not logged in as root run 'su' before this command. (Default password is 'alpine' - it's wise to change this.)" 1>&2 
echo "Look here how to change it:"
echo "https://cydia.saurik.com/password.html"
   exit 1

fi

################
# Set Variables
gversion="iDenT1FIEr" #Identifier
gversionname="vErs10Nname" #Name

################
echo "---Welcome to $gversionname.---"
echo "Made by EthanRDoesMC and mehulrao."

case $1 in
"") 
echo
echo "---USAGE---"
echo
echo "$0 hold: run directly after install of $gversionname. It will prevent cydia from removing Gandalf automatically."
echo
echo "$0 rmhold: run before update or uninstall to let Cydia remove $gversionname."
 ;;
"hold")
echo "Add hold to $gversionname..."
echo "$gversion hold" | dpkg --set-selections
 ;;
 "rmhold")
echo "Remove hold from $gversionname..."
echo "$gversion install" | dpkg --set-selections
 ;;
 *)
echo "ERROR: invalid parameter $1"
echo
echo "---USAGE---"
echo
echo "$0 hold: run directly after install of $gversionname. It will prevent cydia from removing Gandalf automatically"
echo
echo "$0 rmhold: run before update or uninstall to let Cydia remove $gversionname."
;;
 esac
 echo "Thank you for using Gandalf."
