#!/bin/bash
#
# Gandalf executable
# A script for endusers to manage the package.
# provides an easy way for them to block removal of the package

#Variables
PKG_PACKAGE="io.github.ethanrdoesmc.gandalf102"
PKG_NAME="Gandalf for Yalu102"


#Main script

#Check for root
if [[ ${EUID} -ne 0 ]]; then
  echo "ERROR: This script needs root permissions."
  echo
  echo "Please run 'su' before running this command. (Default password is 'alpine' - it's wise to change this.)"
  echo "Reference for changing root password: https://cydia.saurik.com/password.html"
fi

echo "${PKG_NAME} - Let this tweak say \"You shall not pass!\" to incompatible tweaks"

#Main switc
case $1 in
  "hold")
    echo "Adding hold status to ${PKG_NAME}"
	echo "${PKG_PACKAGE} hold" | dpkg --set-selections
	;;
  "rmhold")
    echo "Removing hold status to ${PKG_NAME}"
	echo "${PKG_PACKGE} install" | dpkg --set-selections
	;;
  *)
    echo "Usage:"
	echo "$0 hold - Adds the \"Hold\" status to ${PKG_NAME} to block removal of the package"
	echo
	echo "$0 rmhold - removes the \"Hold\" status to allow removal of ${PKG_NAME}"
	;;
esac
