#!/bin/bash

#Main script
echo "Installing the Gandalf application..."
echo "Unpacking…"

tar -xvf /var/mobile/Downloads/Gandalf/Gandalf.app.tar.gz -C /Applications/
echo "App installed..."


echo "Cleaning up files.."

rm -rf /var/mobile/Downloads/Gandalf


echo "Please Wait... running uicache..."
uicache


echo
echo "--- Now please run 'gandalf hold'! Just to be safe. ---"
echo
echo "The app has the command, if you forget."
echo
echo "This command has to run after 'su' have logged in as root, so run it after 'su' in e.g. MTerminal."

echo "Temporary command permissions fix running"
chmod 0755 /usr/bin/gandalf
echo "Done! In the future you (hopefully) won't have to see this"
echo
echo "Thanks for using Gandalf!"
