#!/bin/bash


#Variables
RED='\033[0;31m' # Define RED as red
NC='\033[0m' # Define NC as no color

#Main script
echo "Installing the Gandalf application..."
echo "Unpacking…"

tar -xvf /var/mobile/Downloads/Gandalf102/Gandalf.app.tar.gz -C /Applications/
echo "App installed..."


echo "Cleaning up files.."

rm -rf /var/mobile/Downloads/Gandalf102


echo "Please Wait... running uicache..."
uicache


echo
echo -e "${RED}--- Now please run 'gAndAlfh0LdC0mMand hold'! Just to be save. ---${NC}"
echo
echo "This command has to run after 'su' have logged in as root, so run it after 'su' in e.g. MTerminal."
