#!/bin/bash

#Main script
echo "Installing the Gandalf application..."
echo "Unpacking…"

tar -xf /var/mobile/Downloads/Gandalf/Gandalf.app.tar.gz -C /Applications/
echo "App installed..."


echo "Cleaning up files..."

rm -rf /var/mobile/Downloads/Gandalf


echo "Please wait... Running uicache..."
uicache

echo "Temporary command permissions fix running"
chmod 0755 /usr/bin/gandalf
echo "Done! In the future you (hopefully) won't have to see this."
echo
echo "--- Now please run 'gandalf hold'! Just to be safe. ---"
echo
echo "--Why should you do that?--"
echo "This command prevents Cydia (better dpkg) from removing Gandalf automatically. If you don't execute this command you could install tweaks usually blocked by Gandalf if something removed Gandalf."
echo
echo "--How to do that?--"
echo
echo "In a terminal emulator like 'MTerminal' execute following commands:"
echo 
echo "   'su' to login as root (Administrator / superuser) default password: 'alpine'"
echo "   'gandalf hold' (to prevent other tweaks from removing Gandalf)"
echo
echo "That's it. After you have executed these commands you can close MTerminal."
echo "Afraid of forgetting them? There is an app on your Homescreen which shows you this command."
sleep 5
echo
echo "Thanks for using Gandalf! (Wow you read this!)"
sleep 2
