#!/bin/bash
echo "Removing the Gandalf application…"
rm -rf /Applications/Gandalf.app
rm -rf /usr/bin/gandalf #Needed? Doesn't dpkg already do this -jonisc
echo "Finished removing the Gandalf application"
#really, you forgot the quotation mark? ugh... thank goodness dpkg tries the prerm from the newpackage if the old package prerm fails... -ethan
