#!/bin/bash

echo "This needs su to run. If it doesn't work... that's why. Run 'su' (the default password is alpine) and then try again."

sleep 2

echo "Gandalf"

sleep 1

echo "Created by EthanRDoesMC and mehulrao"

sleep 1

echo "Setting up Gandalf-portal"

sleep 1


echo "Adding a dpkg hold to Gandalf (prevents Cydia from auto-removing Gandalf when a blacklisted tweak is found)."

echo "io.github.gandalf.portal hold" | dpkg --set-selections

sleep 1

echo "If you saw a dpkg error, please run 'su'."

sleep 1

echo "If not, then Gandalf has successfully been set up. Yay!"

sleep 1

echo "There's nothing more to do. Gandalf will block blacklisted tweaks from getting into the Cydia queue."

sleep 1

echo "Thanks for using Gandalf."