#!/bin/bash

# Make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root. Please run 'su' before (the default password is alpine) and then try again." 1>&2 
   exit 1
fi

echo "---Gandalf---"

sleep 1

echo "Created by EthanRDoesMC and mehulrao"

sleep 1

echo "Setting up Gandalf102..."

sleep 1

echo "Adding a dpkg hold to Gandalf (prevents Cydia from auto-removing Gandalf when a blacklisted tweak is found)."

echo "io.github.ethanrdoesmc.gandalf102 hold" | dpkg --set-selections

sleep 1

echo "There's nothing more to do. Gandalf will block blacklisted tweaks from getting into the Cydia queue."

sleep 1

echo "Thanks for using Gandalf."